# Generated by Django 2.2.3 on 2019-07-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=50)),
                ('program_name', models.CharField(max_length=50)),
                ('collision_number', models.IntegerField()),
                ('on_or_off', models.BooleanField()),
            ],
        ),
    ]
