# Generated by Django 2.2.3 on 2019-08-01 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('robot_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('collision_number', models.IntegerField()),
                ('on_or_off', models.BooleanField()),
                ('robot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadingData.Robot')),
            ],
        ),
    ]
