# Generated by Django 2.2.4 on 2019-08-20 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=50, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RobotError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('robot_error', models.CharField(max_length=200)),
                ('robot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadingData.Robot')),
            ],
        ),
        migrations.CreateModel(
            name='RobotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('collision_number', models.PositiveSmallIntegerField()),
                ('on_or_off', models.BooleanField()),
                ('robot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadingData.Robot')),
            ],
        ),
    ]
