# Generated by Django 2.2.4 on 2019-08-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotdata',
            name='robot_error',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='robotdata',
            name='collision_number',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
