# Generated by Django 2.2.4 on 2019-08-05 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingData', '0002_auto_20190805_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robotdata',
            name='robot_error',
        ),
        migrations.CreateModel(
            name='RobotError',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('robot_error', models.CharField(max_length=200)),
                ('robot_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uploadingData.Robot')),
            ],
        ),
    ]
