# Generated by Django 2.2.4 on 2019-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingData', '0002_auto_20190820_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
