# Generated by Django 2.2.4 on 2019-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadingData', '0003_auto_20190820_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='robot_name',
            field=models.CharField(max_length=50),
        ),
    ]
